const projects = [
  {
    title: "Portfolio",
    text: "My first React project. You are now watching it :)",
    type: "Web",
    image: "portfolio-project.PNG",
    demo: "http://localhost:5173",
    github: "https://github.com/calKU0/Portfolio",
  },
  {
    title: "Web API",
    text: "A modern Web API built with ASP.NET for seamless and secure data exchange between ERP and WMS systems. It enables integration, process automation, and optimization of warehouse operations.",
    type: "Web",
    image: "api-wms.jpg",
    demo: "",
    github: "https://github.com/calKU0/API_WMS",
  },
  {
    title: "Our Memories",
    text: "An album for couples. My first ASP.NET MVC project",
    image: "ourmemories-project.PNG",
    type: "Web",
    demo: "https://ourmemories.azurewebsites.net",
    github: "https://github.com/calKU0/OurMemories",
  },
  {
    title: "Gamex Business Page",
    text: "Simple static business website for company 'Gamex'",
    image: "gamex-project.PNG",
    type: "Web",
    demo: "https://www.gamex-olkusz.pl",
    github: "https://github.com/calKU0/GamexBusinessPage",
  },
  {
    title: "Backend of e-commerce",
    text: "A simple backend project for e-commerce site using TDD in Java",
    image: "ecommerce-project.jpeg",
    type: "Web",
    demo: "",
    github: "https://github.com/calKU0/TDDWebProject",
  },
  {
    title: "ERP to WMS Data Sync – Automated Integration Service",
    text: "A Windows Service that retrieves master data, such as products and contractors, as well as documents from the ERP system and sends them to the WMS via REST API",
    image: "wms-erp.png",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/WMSSynchroService",
  },
  {
    title: "TCP/IP Gateway – Service for Automation Systems",
    text: "A Windows Service application that communicates with automation systems by sending and receiving data frames via TCP/IP. It enables seamless integration with PLC controllers and PTL (Pick-to-Light) systems, ensuring real-time data exchange for efficient industrial automation and process optimization",
    image: "put-to-light.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/TCPIPAutomationServer",
  },
  {
    title: "Automated API Data Loader",
    text: "A Windows Service application built with .NET that fetches data from an API and seamlessly inserts it into a database. Designed for automation, reliability, and efficient data synchronization",
    image: "api-windows-service.png",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/GaskaApiService",
  },
  {
    title: "Logistics Calendar",
    text: "A simple callendar made for logistic's department where you can manage your delivery and dispatch",
    image: "logistics_calendar-project.PNG",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/KolejkowanieWydan",
  },
  {
    title: "Replacement Part Manager",
    text: "A desktop add-on for Comarch ERP XL, utilizing its Hydra framework. The tool enables users to add replacement part numbers.",
    image: "replacement_part_manager-project.PNG",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/HydraDodajOEM",
  },
  {
    title: "Sales Correction Confirmation Service",
    text: "A Windows Service for automatic confirming sales correction documents using ERP XL API with Unitesting",
    image: "sales_correction_confirmation_service-project.webp",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/AutomatycznePotwierdzanieKorektService",
  },
  {
    title: "Client Visit Planner Service",
    text: "A Windows Service that integrates with the CRM system to automatically assign daily tasks to sales representatives. It downloads and retrieve data from files in SFTP server and then uploads response files",
    image: "client_visit_planner_service-project.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/PrzedstawicieleTrasyService",
  },
  {
    title: "SQL Queries",
    text: "Some of my SQL queries, procedures and triggers hat I have done during my career",
    image: "sql-project.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/SQL",
  },
];
export default projects;
