const projects = [
  {
    title: "Portfolio",
    text: "My first React project. You are now watching it :)",
    type: "Web",
    image: "portfolio-project.PNG",
    demo: "http://localhost:5173",
    github: "https://github.com/calKU0/Portfolio",
    frameworks: "React",
    technologies: "JavaScript, HTML, CSS",
  },
  {
    title: "Web API",
    text: "A modern Web API built with ASP.NET Core for seamless and secure data exchange between ERP and WMS systems.",
    type: "Web",
    image: "api-wms.jpg",
    demo: "",
    github: "https://github.com/calKU0/API_WMS",
    frameworks: "ASP.NET Core, Entity Framework",
    technologies: "C#, REST API, ERP XL API, SQL Server",
  },
  {
    title: "Our Memories",
    text: "An album for couples. My first ASP.NET MVC project",
    image: "ourmemories-project.PNG",
    type: "Web",
    demo: "https://ourmemories.azurewebsites.net",
    github: "https://github.com/calKU0/OurMemories",
    frameworks: "ASP.NET MVC, Entity Framework, Identity Framework",
    technologies: "C#, HTML, CSS, JavaScript, SQL Server",
  },
  {
    title: "Gamex Business Page",
    text: "Simple static business website for company 'Gamex'",
    image: "gamex-project.PNG",
    type: "Web",
    demo: "https://www.gamex-olkusz.pl",
    github: "https://github.com/calKU0/GamexBusinessPage",
    frameworks: "None",
    technologies: "HTML, CSS, JavaScript",
  },
  {
    title: "Backend of e-commerce",
    text: "A simple backend project for e-commerce site using TDD in Java",
    image: "ecommerce-project.jpeg",
    type: "Web",
    demo: "",
    github: "https://github.com/calKU0/TDDWebProject",
    frameworks: "Spring Boot",
    technologies: "Java, JUnit, SQL",
  },
  {
    title: "ERP to WMS Data Sync",
    text: "A Windows Service that retrieves master data and sends them to the WMS via REST API",
    image: "wms-erp.png",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/WMSSynchroService",
    frameworks: ".NET Framework",
    technologies: "C#, REST API, ERP XL API, SQL Server",
  },
  {
    title: "TCP/IP Service for Automation Systems",
    text: "A Windows Service application that communicates with automation systems via TCP/IP.",
    image: "put-to-light.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/TCPIPAutomationServer",
    frameworks: ".NET Framework",
    technologies: "C#, TCP/IP, PLC & PTL Integration",
  },
  {
    title: "Automated API Data Loader",
    text: "A Windows Service application that fetches data from an API and inserts it into a database.",
    image: "api-windows-service.png",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/GaskaApiService",
    frameworks: ".NET Framework",
    technologies: "C#, REST API, SQL Server",
  },
  {
    title: "Logistics Calendar",
    text: "A simple calendar for the logistics department to manage deliveries and dispatches.",
    image: "logistics_calendar-project.PNG",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/KolejkowanieWydan",
    frameworks: "CDNXL Hydra, .NET Framework",
    technologies: "C#, SQL Server",
  },
  {
    title: "Replacement Part Manager",
    text: "A desktop add-on for Comarch ERP XL, utilizing its Hydra framework.",
    image: "replacement_part_manager-project.PNG",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/HydraDodajOEM",
    frameworks: "CDNXL Hydra, .NET Framework",
    technologies: "C#, SQL Server",
  },
  {
    title: "Sales Correction Confirmation Service",
    text: "A Windows Service for automatically confirming sales correction documents using ERP XL API.",
    image: "sales_correction_confirmation_service-project.webp",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/AutomatycznePotwierdzanieKorektService",
    frameworks: ".NET Framework",
    technologies: "C#, ERP XL API, Unit Testing, SQL Server",
  },
  {
    title: "Client Visit Planner Service",
    text: "A Windows Service that integrates with the CRM system to assign daily tasks to sales representatives.",
    image: "client_visit_planner_service-project.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/PrzedstawicieleTrasyService",
    frameworks: ".NET Framework",
    technologies: "C#, FTP, SQL Server",
  },
  {
    title: "SQL Queries",
    text: "Some of my SQL queries, procedures, and triggers that I have done during my career",
    image: "sql-project.jpg",
    type: "Other",
    demo: "",
    github: "https://github.com/calKU0/SQL",
    frameworks: "None",
    technologies: "T-SQL, SQL Server",
  },
];

export default projects;
